# 攝影機參數設定
CAM_INDEX = 0
WIDTH = 640
HEIGHT = 480

# 危險門檻設定
DANGER_THRESHOLD = 4.0
SAMPLE_STRIDE = 3
COOLDOWN_MS = 10000

# 最大危險幀與危險幀連續數量的設定，避免誤判
DANGER_FRAMES_REQUIRED = 3

SERIAL_PORT = "/dev/ttyUSB0"
BAUDRATE = 115200

STATE_STOP = 0
STATE_FORWARD = 1

STATE_KEYBOARD_MANUAL = 2

KEYBOARD_SPEED_STEP = 0.1
KEYBOARD_TURN_STEP = 0.1

MAX_SPEED = 0.5
MIN_SPEED = -0.5