# 攝影機參數設定
CAM_INDEX = 0
WIDTH = 640
HEIGHT = 480

# 危險門檻設定
DANGER_THRESHOLD = 2.0
SAMPLE_STRIDE = 6
COOLDOWN_MS = 5000

# 最大危險幀與危險幀連續數量的設定，避免誤判
DANGER_FRAMES_REQUIRED = 3

SERIAL_PORT = "/dev/ttyUSB0"
BAUDRATE = 115200

STATE_STOP = 0
STATE_FORWARD = 1